apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lemur-python
  janus-idp.io/tekton: lemur-python
  backstage.io/kubernetes-id: lemur-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lemur-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
